# Generated by Django 4.2.10 on 2024-06-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpDeskApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
