# Generated by Django 4.2.10 on 2024-06-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpDeskApp", "0004_supportticket_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticket",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
