# Generated by Django 5.0.6 on 2024-06-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpDeskApp", "0005_alter_supportticket_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="is_reply_draft",
            field=models.BooleanField(default=True),
        ),
    ]
